# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ContraintsFullController.xdc

# Block Designs: bd/FullController_GPIOBlock/FullController_GPIOBlock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock || ORIG_REF_NAME==FullController_GPIOBlock} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_TopLevel_0_0/FullController_GPIOBlock_TopLevel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_TopLevel_0_0 || ORIG_REF_NAME==FullController_GPIOBlock_TopLevel_0_0} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_axi_gpio_0_0 || ORIG_REF_NAME==FullController_GPIOBlock_axi_gpio_0_0} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_1/FullController_GPIOBlock_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_axi_gpio_0_1 || ORIG_REF_NAME==FullController_GPIOBlock_axi_gpio_0_1} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_2/FullController_GPIOBlock_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_axi_gpio_0_2 || ORIG_REF_NAME==FullController_GPIOBlock_axi_gpio_0_2} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_processing_system7_0_0/FullController_GPIOBlock_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_processing_system7_0_0 || ORIG_REF_NAME==FullController_GPIOBlock_processing_system7_0_0} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_xbar_0/FullController_GPIOBlock_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_xbar_0 || ORIG_REF_NAME==FullController_GPIOBlock_xbar_0} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_ps7_0_axi_periph_0/FullController_GPIOBlock_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_ps7_0_axi_periph_0 || ORIG_REF_NAME==FullController_GPIOBlock_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_rst_ps7_0_50M_0/FullController_GPIOBlock_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_rst_ps7_0_50M_0 || ORIG_REF_NAME==FullController_GPIOBlock_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_auto_pc_0/FullController_GPIOBlock_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullController_GPIOBlock_auto_pc_0 || ORIG_REF_NAME==FullController_GPIOBlock_auto_pc_0} -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.gen/sources_1/bd/FullController_GPIOBlock/FullController_GPIOBlock_ooc.xdc
