# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.srcs/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1.xci
# IP: The module: 'FullControllerBlockDesign_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.gen/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullControllerBlockDesign_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.gen/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullControllerBlockDesign_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.gen/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullControllerBlockDesign_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.srcs/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1.xci
# IP: The module: 'FullControllerBlockDesign_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.gen/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullControllerBlockDesign_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.gen/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullControllerBlockDesign_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.gen/sources_1/bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullControllerBlockDesign_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
