# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
# IP: The module: 'design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
# IP: The module: 'design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/arwen/OneDrive - Office 365 Fontys/Documenten/Vivado + Xilinx/Tutorials/IndividualAssignment2Encoder/IndividualAssignment2Encoder.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
