# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.srcs/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0.xci
# IP: The module: 'FullController_GPIOBlock_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.gen/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullController_GPIOBlock_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.gen/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullController_GPIOBlock_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.gen/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullController_GPIOBlock_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.srcs/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0.xci
# IP: The module: 'FullController_GPIOBlock_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.gen/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullController_GPIOBlock_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.gen/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullController_GPIOBlock_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullController_GPIO/FullController_GPIO/FullController_GPIO.gen/sources_1/bd/FullController_GPIOBlock/ip/FullController_GPIOBlock_axi_gpio_0_0/FullController_GPIOBlock_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FullController_GPIOBlock_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
