# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo_Z7Master.xdc

# Block Designs: bd/FullControllerBlockDesign/FullControllerBlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign || ORIG_REF_NAME==FullControllerBlockDesign} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_TopLevel_0_0/FullControllerBlockDesign_TopLevel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_TopLevel_0_0 || ORIG_REF_NAME==FullControllerBlockDesign_TopLevel_0_0} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_0/FullControllerBlockDesign_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_axi_gpio_0_0 || ORIG_REF_NAME==FullControllerBlockDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_1/FullControllerBlockDesign_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_axi_gpio_0_1 || ORIG_REF_NAME==FullControllerBlockDesign_axi_gpio_0_1} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_axi_gpio_0_2/FullControllerBlockDesign_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_axi_gpio_0_2 || ORIG_REF_NAME==FullControllerBlockDesign_axi_gpio_0_2} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_processing_system7_0_0/FullControllerBlockDesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_processing_system7_0_0 || ORIG_REF_NAME==FullControllerBlockDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_xbar_0/FullControllerBlockDesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_xbar_0 || ORIG_REF_NAME==FullControllerBlockDesign_xbar_0} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_ps7_0_axi_periph_0/FullControllerBlockDesign_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==FullControllerBlockDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_rst_ps7_0_50M_0/FullControllerBlockDesign_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_rst_ps7_0_50M_0 || ORIG_REF_NAME==FullControllerBlockDesign_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/FullControllerBlockDesign/ip/FullControllerBlockDesign_auto_pc_0/FullControllerBlockDesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FullControllerBlockDesign_auto_pc_0 || ORIG_REF_NAME==FullControllerBlockDesign_auto_pc_0} -quiet] -quiet

# XDC: c:/VivadosBeingAProblem/AES/FullControllerGPIO/FullController2.gen/sources_1/bd/FullControllerBlockDesign/FullControllerBlockDesign_ooc.xdc
